name: helloworld
version: 1

libraries:
- name: flask
  version: "0.10.1"

- name: flask-sqlalchemy
  version: "2.0"

- name: Jinja2
  version: "2.7.3"

- name: markupsafe
  version: "0.23"

- name: sqlalchemy
  version: "0.9.8"

- name: werkzeug
  version: "0.10.1"

- name: flask-wtf
  version: "0.11"

- name: wtforms
  version: "2.0.2"

handlers:
- url: /static
  static_dir: app/static